"""
help_content.py
Uygulama icindeki "Bilgi Merkezi" sayfasinin (launcher/chameleon_gui.py)
ve arac ekranlarindaki ("Bu ne demek?" linkleri, gui_v2.py) AYNI kaynaktan
okudugu konu anlatimlari. Icerik burada TEK yerde tutulur ki iki yerde
ayni metnin farkli kopyalari birbirinden kopmasin.

Yeni bir konu eklemek icin HELP_TOPICS listesine {"key", "title", "body"}
seklinde bir sozluk eklemek yeterli -- "title"/"body" artik dil-anahtarli
sozlukler (tr/en/es/de/pt/fr), get_topic(key, lang) bunlardan lang'a uygun
olani secip duz string olarak dondurur. gui_v2.py/ram_gui.py'nin kendi
arac ekranlari hala Turkce-only oldugu icin (bilincli kapsam siniri,
bkz. CLAUDE.md) oradaki get_topic() cagrilari lang parametresini hic
gecmiyor -- varsayilan "tr" kullanilir.
"""

HELP_TOPICS = [
    {
        "key": "host_key_verification",
        "title": {
            "tr": "Sunucu Kimlik Doğrulama (Host Key) Nedir?",
            "en": "What Is Host Key Verification?",
            "es": "¿Qué es la Verificación de Identidad del Servidor (Host Key)?",
            "de": "Was ist Server-Identitätsprüfung (Host Key)?",
            "pt": "O Que É a Verificação de Identidade do Servidor (Host Key)?",
            "fr": "Qu'est-ce que la Vérification d'Identité du Serveur (Host Key) ?",
        },
        "body": {
            "tr": (
                "SSH ile bağlandığınızda sunucu size kendini tanıtan bir dijital kimlik "
                "(host key) sunar -- bu her bağlantıda otomatik olur, sizin/bizim "
                "müdahale ettiğimiz bir şey değildir.\n\n"
                "Bu sunucuya bilgisayarınızdan daha önce hiç bağlanılmadıysa, bu kimliğin "
                "gerçekten hedeflediğiniz cihaza mı yoksa ağ üzerinde onun yerine cevap "
                "veren başka bir cihaza mı ait olduğu tek başına bilinemez. Kullanıcı "
                "adı/şifrenin doğru olması sadece o cihaza giriş yapma yetkiniz "
                "olduğunu gösterir, karşıdaki cihazın kimliğini değil.\n\n"
                "Alınan verinin bütünlüğü ayrıca hash karşılaştırmasıyla da kontrol "
                "edilir, ama bu farklı bir şeyi kanıtlar: verinin aktarım sırasında "
                "bozulmadığını -- hangi cihazdan geldiğini değil. Bu yüzden iki kontrol "
                "birbirinin yerine geçmez (bkz. \"Hash / Bütünlük Doğrulaması Nedir?\").\n\n"
                "\"Sıkı doğrula\" seçiliyken, kimliği önceden doğrulanmamış bir sunucuya "
                "bağlanmak reddedilir. \"Doğrulamayı atla\" seçildiğinde (örn. şahsa "
                "ait, ilk kez bağlanılan bir cihazda) kontrol tamamen KAPANMAZ: "
                "Chameleon, ilk bağlantıda sunucunun kimliğini kendi kaydına alır; "
                "aynı cihaza tekrar bağlandığınızda bu kayıtla karşılaştırır. Kayıtla "
                "eşleşmeyen bir kimlik gelirse (sunucu değişmiş ya da araya biri "
                "girmiş olabilir) bağlantı yine reddedilir -- \"atla\" sadece İLK "
                "bağlantıdaki bilinmezliği kabul eder, sonrasında tutarlılığı takip "
                "etmeye devam eder. Bu tercih delil zincirine ayrıca kaydedilir; "
                "böylece ileride \"bu görüntünün gerçekten o cihazdan alındığı nasıl "
                "biliniyor?\" sorusuna, hangi kontrollerin yapıldığı açıkça gösterilerek cevap "
                "verilebilir."
            ),
            "en": (
                "When you connect over SSH, the server presents a digital identity (host "
                "key) that identifies itself -- this happens automatically on every "
                "connection, it isn't something you or we intervene in.\n\n"
                "If your computer has never connected to this server before, there is no "
                "way to know on its own whether this identity truly belongs to the device "
                "you intended to reach, or to some other device answering in its place on "
                "the network. A correct username/password only proves you have the "
                "authority to log into that device -- not the identity of the device on "
                "the other end.\n\n"
                "The integrity of the data received is also checked separately via hash "
                "comparison, but that proves something different: that the data was not "
                "corrupted in transit -- not which device it came from. That's why the "
                "two checks don't substitute for each other (see \"What Is Hash / "
                "Integrity Verification?\").\n\n"
                "With \"Strict verification\" selected, connecting to a server whose "
                "identity hasn't been previously verified is refused. When \"Skip "
                "verification\" is selected (e.g. on a personally owned device you're "
                "connecting to for the first time), the check is NOT disabled entirely: "
                "on the first connection Chameleon records the server's identity itself; "
                "on any later connection to the same device, it compares against that "
                "record. If an identity arrives that doesn't match the record (the "
                "server may have changed, or someone may be intercepting the "
                "connection), the connection is still refused -- \"skip\" only accepts "
                "the unknown on the VERY FIRST connection, and keeps enforcing "
                "consistency afterward. This choice is separately recorded in the chain "
                "of custody, so that a future question like \"how do we know this image "
                "was really taken from that device?\" can be answered clearly, by "
                "showing exactly which checks were performed."
            ),
            "es": (
                "Al conectarse por SSH, el servidor presenta una identidad digital (host "
                "key) que lo identifica -- esto ocurre automáticamente en cada conexión, "
                "no es algo en lo que usted o nosotros intervengamos.\n\n"
                "Si su equipo nunca se ha conectado antes a este servidor, no hay forma "
                "de saber por sí solo si esta identidad pertenece realmente al "
                "dispositivo al que quiere llegar, o a otro dispositivo que responde en "
                "su lugar en la red. Un nombre de usuario/contraseña correctos solo "
                "demuestran que tiene autorización para iniciar sesión en ese "
                "dispositivo -- no la identidad del dispositivo al otro lado.\n\n"
                "La integridad de los datos recibidos también se comprueba por separado "
                "mediante comparación de hash, pero eso demuestra algo distinto: que los "
                "datos no se corrompieron durante la transferencia -- no de qué "
                "dispositivo provienen. Por eso las dos comprobaciones no se sustituyen "
                "entre sí (véase \"¿Qué es la Verificación de Hash / Integridad?\").\n\n"
                "Con \"Verificación estricta\" seleccionada, se rechaza conectarse a un "
                "servidor cuya identidad no se ha verificado previamente. Cuando se "
                "selecciona \"Omitir verificación\" (p. ej. en un dispositivo personal "
                "al que se conecta por primera vez), la comprobación NO se desactiva por "
                "completo: en la primera conexión, Chameleon registra la identidad del "
                "servidor; en conexiones posteriores al mismo dispositivo, la compara "
                "con ese registro. Si llega una identidad que no coincide con el "
                "registro (el servidor pudo haber cambiado, o alguien podría estar "
                "interceptando la conexión), la conexión se rechaza igualmente -- "
                "\"omitir\" solo acepta lo desconocido en la PRIMERA conexión, y después "
                "sigue exigiendo consistencia. Esta elección queda también registrada en "
                "la cadena de custodia, de modo que una pregunta futura como \"¿cómo "
                "sabemos que esta imagen realmente se obtuvo de ese dispositivo?\" pueda "
                "responderse con claridad, mostrando exactamente qué comprobaciones se "
                "realizaron."
            ),
            "de": (
                "Wenn Sie sich per SSH verbinden, präsentiert der Server eine digitale "
                "Identität (Host-Key), die ihn ausweist -- dies geschieht bei jeder "
                "Verbindung automatisch, es ist nichts, worauf Sie oder wir Einfluss "
                "nehmen.\n\n"
                "Wenn Ihr Computer noch nie zuvor mit diesem Server verbunden war, lässt "
                "sich allein daraus nicht wissen, ob diese Identität wirklich zu dem "
                "Gerät gehört, das Sie erreichen wollen, oder zu einem anderen Gerät, "
                "das im Netzwerk an seiner Stelle antwortet. Ein korrekter "
                "Benutzername/Passwort beweist nur, dass Sie berechtigt sind, sich bei "
                "diesem Gerät anzumelden -- nicht die Identität des Geräts auf der "
                "anderen Seite.\n\n"
                "Die Integrität der empfangenen Daten wird zusätzlich separat per "
                "Hash-Vergleich geprüft, aber das beweist etwas anderes: dass die Daten "
                "während der Übertragung nicht beschädigt wurden -- nicht, von welchem "
                "Gerät sie stammen. Deshalb ersetzt keine der beiden Prüfungen die "
                "andere (siehe \"Was ist Hash-/Integritätsprüfung?\").\n\n"
                "Bei ausgewählter \"Strenge Prüfung\" wird die Verbindung zu einem "
                "Server, dessen Identität nicht zuvor verifiziert wurde, abgelehnt. Wird "
                "\"Prüfung überspringen\" gewählt (z. B. bei einem privaten Gerät, mit "
                "dem Sie sich zum ersten Mal verbinden), wird die Prüfung NICHT "
                "vollständig deaktiviert: Bei der ersten Verbindung zeichnet Chameleon "
                "die Identität des Servers selbst auf; bei einer erneuten Verbindung zum "
                "selben Gerät wird gegen diesen Datensatz verglichen. Kommt eine "
                "Identität an, die nicht mit dem Datensatz übereinstimmt (der Server "
                "könnte sich geändert haben, oder jemand könnte die Verbindung "
                "abfangen), wird die Verbindung trotzdem abgelehnt -- \"Überspringen\" "
                "akzeptiert das Unbekannte nur bei der ALLERERSTEN Verbindung und "
                "überwacht danach weiterhin die Konsistenz. Diese Entscheidung wird "
                "zusätzlich in der Beweismittelkette festgehalten, sodass eine spätere "
                "Frage wie \"Woher wissen wir, dass dieses Abbild wirklich von diesem "
                "Gerät stammt?\" klar beantwortet werden kann, indem genau gezeigt wird, "
                "welche Prüfungen durchgeführt wurden."
            ),
            "pt": (
                "Ao conectar-se via SSH, o servidor apresenta uma identidade digital "
                "(host key) que o identifica -- isso ocorre automaticamente em cada "
                "conexão, não é algo em que você ou nós intervimos.\n\n"
                "Se o seu computador nunca se conectou antes a esse servidor, não há "
                "como saber sozinho se essa identidade realmente pertence ao dispositivo "
                "que você pretende alcançar, ou a outro dispositivo respondendo em seu "
                "lugar na rede. Um nome de usuário/senha corretos apenas provam que você "
                "tem autorização para entrar nesse dispositivo -- não a identidade do "
                "dispositivo do outro lado.\n\n"
                "A integridade dos dados recebidos também é verificada separadamente por "
                "comparação de hash, mas isso comprova algo diferente: que os dados não "
                "foram corrompidos durante a transferência -- não de qual dispositivo "
                "eles vieram. Por isso as duas verificações não substituem uma à outra "
                "(veja \"O Que É Verificação de Hash / Integridade?\").\n\n"
                "Com \"Verificação estrita\" selecionada, conectar-se a um servidor cuja "
                "identidade não foi verificada anteriormente é recusado. Quando \"Pular "
                "verificação\" é selecionado (ex.: em um dispositivo pessoal ao qual "
                "você está se conectando pela primeira vez), a verificação NÃO é "
                "totalmente desativada: na primeira conexão, o Chameleon registra a "
                "identidade do servidor; em conexões posteriores ao mesmo dispositivo, "
                "ele compara com esse registro. Se chegar uma identidade que não "
                "corresponde ao registro (o servidor pode ter mudado, ou alguém pode "
                "estar interceptando a conexão), a conexão ainda é recusada -- \"pular\" "
                "aceita o desconhecido apenas na PRIMEIRA conexão, e depois continua "
                "exigindo consistência. Essa escolha também é registrada na cadeia de "
                "custódia, para que uma pergunta futura como \"como sabemos que essa "
                "imagem foi realmente obtida daquele dispositivo?\" possa ser respondida "
                "com clareza, mostrando exatamente quais verificações foram realizadas."
            ),
            "fr": (
                "Lorsque vous vous connectez via SSH, le serveur présente une identité "
                "numérique (host key) qui l'identifie -- cela se produit automatiquement "
                "à chaque connexion, ce n'est pas quelque chose sur lequel vous ou nous "
                "intervenons.\n\n"
                "Si votre ordinateur ne s'est jamais connecté auparavant à ce serveur, il "
                "est impossible de savoir à lui seul si cette identité appartient "
                "vraiment à l'appareil que vous visez, ou à un autre appareil répondant "
                "à sa place sur le réseau. Un nom d'utilisateur/mot de passe correct "
                "prouve seulement que vous avez l'autorisation de vous connecter à cet "
                "appareil -- pas l'identité de l'appareil en face.\n\n"
                "L'intégrité des données reçues est également vérifiée séparément par "
                "comparaison de hash, mais cela prouve autre chose : que les données "
                "n'ont pas été corrompues pendant le transfert -- pas de quel appareil "
                "elles proviennent. C'est pourquoi les deux vérifications ne se "
                "substituent pas l'une à l'autre (voir \"Qu'est-ce que la Vérification "
                "de Hash / Intégrité ?\").\n\n"
                "Avec \"Vérification stricte\" sélectionnée, la connexion à un serveur "
                "dont l'identité n'a pas été préalablement vérifiée est refusée. "
                "Lorsque \"Ignorer la vérification\" est sélectionné (p. ex. sur un "
                "appareil personnel auquel vous vous connectez pour la première fois), "
                "le contrôle n'est PAS entièrement désactivé : lors de la première "
                "connexion, Chameleon enregistre lui-même l'identité du serveur ; lors "
                "d'une reconnexion ultérieure au même appareil, il la compare à cet "
                "enregistrement. Si une identité ne correspondant pas à l'enregistrement "
                "se présente (le serveur a peut-être changé, ou quelqu'un intercepte "
                "peut-être la connexion), la connexion est quand même refusée -- "
                "\"ignorer\" n'accepte l'inconnu que lors de la TOUTE PREMIÈRE "
                "connexion, et continue ensuite à vérifier la cohérence. Ce choix est "
                "également enregistré dans la chaîne de possession, afin qu'une "
                "question future comme \"comment sait-on que cette image provient "
                "vraiment de cet appareil ?\" puisse recevoir une réponse claire, en "
                "montrant exactement quels contrôles ont été effectués."
            ),
        },
    },
    {
        "key": "live_vs_offline_acquisition",
        "title": {
            "tr": "Live ve Offline Acquisition (Yazma Engelleme) Nedir?",
            "en": "What Are Live and Offline Acquisition (Write Blocking)?",
            "es": "¿Qué son la Adquisición en Vivo (Live) y sin Conexión (Offline) (Bloqueo de Escritura)?",
            "de": "Was sind Live- und Offline-Erfassung (Schreibschutz)?",
            "pt": "O Que São Aquisição Live e Offline (Bloqueio de Escrita)?",
            "fr": "Que Sont l'Acquisition Live et Offline (Blocage en Écriture) ?",
        },
        "body": {
            "tr": (
                "Hedef diski görüntülerken iki moddan biri seçilir. Buradaki ayrım "
                "\"hedef makine açık mı\" değildir -- SSH ile bağlanabilmek için makine "
                "zaten açık/erişilebilir olmak ZORUNDADIR, bu her iki modda da geçerlidir. "
                "Asıl ayrım, alınacak DİSKİN o makinenin ÇALIŞAN sistemi tarafından "
                "kullanılıp kullanılmadığıdır:\n\n"
                "Live Acquisition: hedef disk, üzerinde çalışan bir sistemin (örn. "
                "kapatılamayan bir sunucunun) KENDİ işletim/veri diskidir -- disk o "
                "sistem tarafından aktif olarak kullanılır, durdurulursa ya da salt-okunur "
                "kilitlenirse sistem çalışmayı durdurabilir. Bu yüzden disk OLDUĞU GİBİ, "
                "kilitlenmeden okunur -- sistemi durdurmadan başka bir seçenek yoktur.\n\n"
                "Offline Acquisition: hedef makine erişilebilir olsa bile, alınacak disk o "
                "makinenin çalışan sistemi tarafından aktif kullanımda DEĞİLDİR (örn. "
                "takılı ama bağlanmamış/mount edilmemiş ikincil bir sürücü, ya da "
                "incelenen sistem kapatılıp diski başka bir makineye takılmış). Böyle bir "
                "diski durdurmadan/bozmadan salt-okunur kilitlemek mümkündür -- Chameleon, "
                "imaj almadan ÖNCE diski bu şekilde kilitler; \"write-blocker\" denen bu "
                "adım, imaj alma işleminin KENDİSİNİN diskte hiçbir değişikliğe sebep "
                "olmadığını ispatlanabilir şekilde garanti eder.\n\n"
                "Hangi modun seçildiği ve yazma engellemenin uygulanıp uygulanmadığı, "
                "rapora ve delil zincirine otomatik olarak kaydedilir. Emin değilseniz: "
                "disk hâlâ çalışan bir sistemin parçasıysa Live, değilse Offline "
                "seçilmelidir -- Offline, ekstra bir bütünlük garantisi sağladığı için "
                "mümkün olduğunda tercih edilir.\n\n"
                "Live Acquisition'ın bir sınırı var: diskin blokları TEK SEFERDE "
                "değil, sırayla (bir süreye yayılarak) okunur. Disk bu süre boyunca "
                "aktif kullanımda olduğu için, imajın farklı kısımları diskin farklı "
                "ANLARINA ait olabilir -- yani tek bir dondurulmuş kareye değil, "
                "alma süresince değişmiş olabilecek bir duruma karşılık gelir. Bu, "
                "anlık bir kopya (snapshot) alan araçların önlediği, ama Live modun "
                "doğası gereği önleyemediği bir durumdur."
            ),
            "en": (
                "One of two modes is chosen when imaging the target disk. The "
                "distinction here is NOT \"is the target machine on\" -- the machine "
                "must already be on/reachable to connect via SSH at all, and that's "
                "true for both modes. The real distinction is whether the disk being "
                "imaged is being used by that machine's RUNNING system:\n\n"
                "Live Acquisition: the target disk is the running system's OWN "
                "operating/data disk (e.g. a server that can't be shut down) -- the "
                "disk is actively used by that system, and stopping it or locking it "
                "read-only could stop the system from working. So the disk is read "
                "AS-IS, without locking it -- there is no option other than not "
                "stopping the system.\n\n"
                "Offline Acquisition: even if the target machine is reachable, the disk "
                "being imaged is NOT in active use by that machine's running system "
                "(e.g. a secondary drive that's attached but not mounted, or the "
                "examined system was shut down and its disk attached to another "
                "machine). Such a disk CAN be locked read-only without "
                "stopping/disturbing it -- Chameleon locks the disk this way BEFORE "
                "imaging; this step, called a \"write-blocker\", verifiably guarantees "
                "that the acquisition process ITSELF causes no change to the disk "
                "whatsoever.\n\n"
                "Which mode was selected, and whether write-blocking was applied, is "
                "recorded automatically in the report and the chain of custody. If "
                "unsure: choose Live if the disk is still part of a running system, "
                "Offline if it isn't -- Offline is preferred whenever possible, since it "
                "provides an extra integrity guarantee.\n\n"
                "Live Acquisition has one limitation: the disk's blocks are read "
                "sequentially over a period of time, NOT all at once. Because the disk "
                "stays actively in use during that time, different parts of the image "
                "may correspond to different MOMENTS of the disk -- meaning the result "
                "doesn't reflect a single frozen snapshot, but a state that may have "
                "changed during the acquisition. This is something snapshot-capable "
                "tools avoid, but that Live mode cannot avoid by its very nature."
            ),
            "es": (
                "Al obtener la imagen del disco destino se elige uno de dos modos. La "
                "distinción aquí NO es \"si la máquina destino está encendida\" -- la "
                "máquina ya debe estar encendida/accesible para poder conectarse por "
                "SSH, y eso aplica en ambos modos. La distinción real es si el DISCO "
                "que se va a obtener está siendo usado por el sistema EN EJECUCIÓN de "
                "esa máquina:\n\n"
                "Adquisición en Vivo (Live): el disco destino es el propio disco de "
                "sistema/datos de un sistema en ejecución (p. ej. un servidor que no se "
                "puede apagar) -- el disco está siendo usado activamente por ese "
                "sistema, y detenerlo o bloquearlo en modo solo lectura podría hacer que "
                "el sistema deje de funcionar. Por eso el disco se lee TAL CUAL, sin "
                "bloquearlo -- no hay otra opción que no detener el sistema.\n\n"
                "Adquisición sin Conexión (Offline): aunque la máquina destino sea "
                "accesible, el disco que se va a obtener NO está en uso activo por el "
                "sistema en ejecución de esa máquina (p. ej. una unidad secundaria "
                "conectada pero no montada, o el sistema examinado fue apagado y su "
                "disco conectado a otra máquina). Un disco así SÍ puede bloquearse en "
                "modo solo lectura sin detenerlo/alterarlo -- Chameleon bloquea el "
                "disco de esta manera ANTES de obtener la imagen; este paso, llamado "
                "\"write-blocker\" (bloqueador de escritura), garantiza de forma "
                "demostrable que el propio proceso de adquisición no causa ningún "
                "cambio en el disco.\n\n"
                "Qué modo se seleccionó y si se aplicó el bloqueo de escritura se "
                "registra automáticamente en el informe y en la cadena de custodia. Si "
                "no está seguro: elija Live si el disco todavía forma parte de un "
                "sistema en ejecución, Offline si no -- Offline se prefiere siempre que "
                "sea posible, ya que aporta una garantía adicional de integridad.\n\n"
                "La Adquisición en Vivo tiene una limitación: los bloques del disco se "
                "leen de forma secuencial a lo largo de un período, NO de una sola vez. "
                "Como el disco permanece en uso activo durante ese tiempo, distintas "
                "partes de la imagen pueden corresponder a distintos MOMENTOS del disco "
                "-- es decir, el resultado no representa una única instantánea "
                "congelada, sino un estado que pudo haber cambiado durante la "
                "adquisición. Esto es algo que las herramientas con capacidad de "
                "snapshot evitan, pero que el modo Live no puede evitar por su propia "
                "naturaleza."
            ),
            "de": (
                "Bei der Abbildung der Zielfestplatte wird einer von zwei Modi gewählt. "
                "Die Unterscheidung hier ist NICHT \"ist die Zielmaschine "
                "eingeschaltet\" -- die Maschine muss bereits eingeschaltet/erreichbar "
                "sein, um überhaupt per SSH verbinden zu können, und das gilt für beide "
                "Modi. Der eigentliche Unterschied ist, ob die zu erfassende "
                "FESTPLATTE vom LAUFENDEN System dieser Maschine verwendet wird:\n\n"
                "Live-Erfassung: Die Zielfestplatte ist die EIGENE "
                "Betriebssystem-/Datenfestplatte eines laufenden Systems (z. B. eines "
                "Servers, der nicht heruntergefahren werden kann) -- die Festplatte "
                "wird von diesem System aktiv genutzt, und ein Anhalten oder eine "
                "Sperrung auf Nur-Lesen könnte dazu führen, dass das System nicht mehr "
                "funktioniert. Deshalb wird die Festplatte SO WIE SIE IST gelesen, ohne "
                "sie zu sperren -- es gibt keine andere Option, als das System nicht "
                "anzuhalten.\n\n"
                "Offline-Erfassung: Selbst wenn die Zielmaschine erreichbar ist, wird "
                "die zu erfassende Festplatte NICHT aktiv vom laufenden System dieser "
                "Maschine verwendet (z. B. ein angeschlossenes, aber nicht "
                "eingehängtes Zweitlaufwerk, oder das untersuchte System wurde "
                "heruntergefahren und seine Festplatte an eine andere Maschine "
                "angeschlossen). Eine solche Festplatte KANN gesperrt werden, ohne sie "
                "anzuhalten/zu stören -- Chameleon sperrt die Festplatte auf diese "
                "Weise, BEVOR das Abbild erstellt wird; dieser als \"Write-Blocker\" "
                "bezeichnete Schritt garantiert nachweisbar, dass der Erfassungsvorgang "
                "SELBST keinerlei Änderung an der Festplatte verursacht.\n\n"
                "Welcher Modus gewählt wurde und ob ein Schreibschutz angewendet "
                "wurde, wird automatisch im Bericht und in der Beweismittelkette "
                "festgehalten. Im Zweifel: Live wählen, wenn die Festplatte noch Teil "
                "eines laufenden Systems ist, Offline, wenn nicht -- Offline wird wann "
                "immer möglich bevorzugt, da es eine zusätzliche Integritätsgarantie "
                "bietet.\n\n"
                "Die Live-Erfassung hat eine Einschränkung: Die Blöcke der Festplatte "
                "werden über einen Zeitraum hinweg nacheinander gelesen, NICHT auf "
                "einmal. Da die Festplatte während dieser Zeit aktiv in Benutzung "
                "bleibt, können verschiedene Teile des Abbilds unterschiedlichen "
                "ZEITPUNKTEN der Festplatte entsprechen -- das Ergebnis entspricht also "
                "keiner einzigen eingefrorenen Momentaufnahme, sondern einem Zustand, "
                "der sich während der Erfassung geändert haben könnte. Dies ist etwas, "
                "das snapshotfähige Werkzeuge vermeiden, was der Live-Modus jedoch "
                "aufgrund seiner Natur nicht vermeiden kann."
            ),
            "pt": (
                "Ao obter a imagem do disco alvo, um de dois modos é escolhido. A "
                "distinção aqui NÃO é \"a máquina alvo está ligada\" -- a máquina já "
                "precisa estar ligada/acessível para conectar via SSH, e isso vale "
                "para os dois modos. A distinção real é se o DISCO a ser obtido está "
                "sendo usado pelo sistema EM EXECUÇÃO daquela máquina:\n\n"
                "Aquisição Live: o disco alvo é o próprio disco de sistema/dados de um "
                "sistema em execução (ex.: um servidor que não pode ser desligado) -- "
                "o disco está sendo usado ativamente por esse sistema, e pará-lo ou "
                "bloqueá-lo em somente leitura pode fazer o sistema parar de "
                "funcionar. Por isso o disco é lido COMO ESTÁ, sem bloqueá-lo -- não "
                "há outra opção além de não parar o sistema.\n\n"
                "Aquisição Offline: mesmo que a máquina alvo esteja acessível, o disco "
                "a ser obtido NÃO está em uso ativo pelo sistema em execução dessa "
                "máquina (ex.: uma unidade secundária conectada mas não montada, ou o "
                "sistema examinado foi desligado e seu disco conectado a outra "
                "máquina). Um disco assim PODE ser bloqueado em somente leitura sem "
                "pará-lo/perturbá-lo -- o Chameleon bloqueia o disco dessa forma ANTES "
                "de obter a imagem; essa etapa, chamada \"write-blocker\" (bloqueador "
                "de escrita), garante de forma comprovável que o próprio processo de "
                "aquisição não causa nenhuma alteração no disco.\n\n"
                "Qual modo foi selecionado e se o bloqueio de escrita foi aplicado é "
                "registrado automaticamente no relatório e na cadeia de custódia. Se "
                "não tiver certeza: escolha Live se o disco ainda faz parte de um "
                "sistema em execução, Offline se não -- o Offline é preferido sempre "
                "que possível, pois fornece uma garantia extra de integridade.\n\n"
                "A Aquisição Live tem uma limitação: os blocos do disco são lidos "
                "sequencialmente ao longo de um período, NÃO de uma só vez. Como o "
                "disco permanece em uso ativo durante esse tempo, partes diferentes da "
                "imagem podem corresponder a MOMENTOS diferentes do disco -- ou seja, "
                "o resultado não representa um único instantâneo congelado, mas um "
                "estado que pode ter mudado durante a aquisição. Isso é algo que "
                "ferramentas com capacidade de snapshot evitam, mas que o modo Live "
                "não pode evitar por sua própria natureza."
            ),
            "fr": (
                "Lors de l'imagerie du disque cible, l'un des deux modes est choisi. La "
                "distinction ici n'est PAS \"la machine cible est-elle allumée\" -- la "
                "machine doit déjà être allumée/accessible pour pouvoir se connecter "
                "via SSH, et cela vaut pour les deux modes. La vraie distinction est de "
                "savoir si le DISQUE à imager est utilisé par le système EN COURS "
                "D'EXÉCUTION de cette machine :\n\n"
                "Acquisition Live : le disque cible est le propre disque "
                "système/données d'un système en cours d'exécution (p. ex. un serveur "
                "qui ne peut pas être arrêté) -- le disque est activement utilisé par "
                "ce système, et l'arrêter ou le verrouiller en lecture seule pourrait "
                "faire cesser son fonctionnement. C'est pourquoi le disque est lu TEL "
                "QUEL, sans le verrouiller -- il n'y a pas d'autre option que de ne pas "
                "arrêter le système.\n\n"
                "Acquisition Offline : même si la machine cible est accessible, le "
                "disque à imager n'est PAS en usage actif par le système en cours "
                "d'exécution de cette machine (p. ex. un disque secondaire branché "
                "mais non monté, ou le système examiné a été arrêté et son disque "
                "branché sur une autre machine). Un tel disque PEUT être verrouillé en "
                "lecture seule sans être arrêté/perturbé -- Chameleon verrouille le "
                "disque de cette façon AVANT l'imagerie ; cette étape, appelée "
                "\"write-blocker\" (bloqueur d'écriture), garantit de manière "
                "vérifiable que le processus d'acquisition LUI-MÊME ne provoque aucune "
                "modification du disque.\n\n"
                "Le mode sélectionné et si le blocage en écriture a été appliqué sont "
                "enregistrés automatiquement dans le rapport et la chaîne de "
                "possession. En cas de doute : choisissez Live si le disque fait "
                "encore partie d'un système en cours d'exécution, Offline sinon -- "
                "Offline est préféré chaque fois que possible, car il apporte une "
                "garantie d'intégrité supplémentaire.\n\n"
                "L'Acquisition Live a une limite : les blocs du disque sont lus "
                "séquentiellement sur une période, PAS en une seule fois. Le disque "
                "restant activement utilisé pendant ce temps, différentes parties de "
                "l'image peuvent correspondre à différents MOMENTS du disque -- "
                "c'est-à-dire que le résultat ne correspond pas à un instantané figé "
                "unique, mais à un état qui a pu changer pendant l'acquisition. C'est "
                "quelque chose que les outils capables de snapshot évitent, mais que le "
                "mode Live ne peut pas éviter de par sa nature même."
            ),
        },
    },
    {
        "key": "chain_of_custody",
        "title": {
            "tr": "Delil Zinciri (Chain of Custody) Nedir?",
            "en": "What Is Chain of Custody?",
            "es": "¿Qué es la Cadena de Custodia?",
            "de": "Was ist die Beweismittelkette (Chain of Custody)?",
            "pt": "O Que É a Cadeia de Custódia?",
            "fr": "Qu'est-ce que la Chaîne de Possession ?",
        },
        "body": {
            "tr": (
                "Delil zinciri, bir dijital delilin ele geçirildiği andan rapora/"
                "mahkemeye sunulana kadar kimin, ne zaman, hangi işlemi yaptığının "
                "kesintisiz kaydıdır. Amacı, ileride \"bu delil değiştirilmiş olabilir "
                "mi, kim müdahale etti?\" sorusuna net cevap verebilmektir.\n\n"
                "Chameleon, imaj alma sırasında yaptığı HER işlemi (bağlantı kuruldu, "
                "disk kilitlendi/kilitlenmedi, hangi blok alındı, hash doğrulandı, "
                "bağlantı koptu/devam edildi, hangi ağ yöntemi kullanıldı vb.) otomatik "
                "olarak zaman damgasıyla bir log dosyasına yazar. Bu log, işlem bitince "
                "oluşturulan rapora dahil edilir.\n\n"
                "Bazı adımlarda sizin yaptığınız bir TERCİH de bu zincire kaydedilir "
                "(örn. sunucu kimlik doğrulamasının atlanması, VPN/Tor kullanımı). Bu, "
                "\"gizli/yanlış bir şey yapıldı\" anlamına gelmez -- tam tersine, hangi "
                "güvenlik kontrollerinin o alma işleminde aktif olup olmadığının "
                "şeffaf bir kaydıdır."
            ),
            "en": (
                "Chain of custody is the unbroken record of who did what, and when, "
                "from the moment a piece of digital evidence is seized until it is "
                "presented in a report/court. Its purpose is to give a clear answer to "
                "a future question like \"could this evidence have been altered, and "
                "did anyone tamper with it?\"\n\n"
                "During acquisition, Chameleon automatically writes EVERY action it "
                "takes (connection established, disk locked/not locked, which block was "
                "acquired, hash verified, connection dropped/resumed, which network "
                "method was used, etc.) to a timestamped log file. This log is included "
                "in the report generated once the operation finishes.\n\n"
                "A CHOICE you make at certain steps is also recorded in this chain (e.g. "
                "skipping server identity verification, using VPN/Tor). This does not "
                "mean \"something hidden/wrong was done\" -- on the contrary, it is a "
                "transparent record of exactly which security checks were or weren't "
                "active during that acquisition."
            ),
            "es": (
                "La cadena de custodia es el registro ininterrumpido de quién hizo qué "
                "y cuándo, desde el momento en que se incauta una evidencia digital "
                "hasta que se presenta en un informe/tribunal. Su propósito es poder "
                "dar una respuesta clara a una pregunta futura como \"¿pudo alterarse "
                "esta evidencia, alguien la manipuló?\".\n\n"
                "Durante la adquisición, Chameleon escribe automáticamente CADA acción "
                "que realiza (conexión establecida, disco bloqueado/no bloqueado, qué "
                "bloque se obtuvo, hash verificado, conexión perdida/reanudada, qué "
                "método de red se usó, etc.) con marca de tiempo en un archivo de "
                "registro. Este registro se incluye en el informe generado al "
                "finalizar la operación.\n\n"
                "Una DECISIÓN que usted toma en ciertos pasos también queda registrada "
                "en esta cadena (p. ej. omitir la verificación de identidad del "
                "servidor, usar VPN/Tor). Esto no significa \"se hizo algo oculto/"
                "incorrecto\" -- al contrario, es un registro transparente de "
                "exactamente qué controles de seguridad estuvieron o no activos "
                "durante esa adquisición."
            ),
            "de": (
                "Die Beweismittelkette ist die lückenlose Aufzeichnung darüber, wer "
                "wann was getan hat, vom Moment der Sicherstellung eines digitalen "
                "Beweismittels bis zu seiner Vorlage in einem Bericht/vor Gericht. Ihr "
                "Zweck ist es, eine spätere Frage wie \"Könnte dieses Beweismittel "
                "verändert worden sein, hat jemand daran manipuliert?\" klar "
                "beantworten zu können.\n\n"
                "Während der Erfassung schreibt Chameleon automatisch JEDE von ihm "
                "durchgeführte Aktion (Verbindung hergestellt, Festplatte "
                "gesperrt/nicht gesperrt, welcher Block erfasst wurde, Hash "
                "verifiziert, Verbindung unterbrochen/fortgesetzt, welche "
                "Netzwerkmethode verwendet wurde usw.) mit Zeitstempel in eine "
                "Protokolldatei. Dieses Protokoll wird in den nach Abschluss des "
                "Vorgangs erstellten Bericht aufgenommen.\n\n"
                "Auch eine von Ihnen bei bestimmten Schritten getroffene ENTSCHEIDUNG "
                "wird in dieser Kette festgehalten (z. B. das Überspringen der "
                "Server-Identitätsprüfung, die Verwendung von VPN/Tor). Das bedeutet "
                "nicht \"es wurde etwas Verstecktes/Falsches getan\" -- im Gegenteil, "
                "es ist eine transparente Aufzeichnung genau darüber, welche "
                "Sicherheitsprüfungen bei dieser Erfassung aktiv waren oder nicht."
            ),
            "pt": (
                "A cadeia de custódia é o registro ininterrupto de quem fez o quê e "
                "quando, desde o momento em que uma evidência digital é apreendida até "
                "ser apresentada em um relatório/tribunal. Seu objetivo é poder dar uma "
                "resposta clara a uma pergunta futura como \"essa evidência poderia ter "
                "sido alterada, alguém a adulterou?\".\n\n"
                "Durante a aquisição, o Chameleon grava automaticamente CADA ação que "
                "realiza (conexão estabelecida, disco bloqueado/não bloqueado, qual "
                "bloco foi adquirido, hash verificado, conexão perdida/retomada, qual "
                "método de rede foi usado etc.) com carimbo de data/hora em um arquivo "
                "de log. Esse log é incluído no relatório gerado ao final da "
                "operação.\n\n"
                "Uma ESCOLHA feita por você em certas etapas também é registrada nessa "
                "cadeia (ex.: pular a verificação de identidade do servidor, usar "
                "VPN/Tor). Isso não significa \"algo oculto/errado foi feito\" -- pelo "
                "contrário, é um registro transparente de exatamente quais controles "
                "de segurança estavam ou não ativos durante aquela aquisição."
            ),
            "fr": (
                "La chaîne de possession est l'enregistrement ininterrompu de qui a "
                "fait quoi et quand, depuis le moment où une preuve numérique est "
                "saisie jusqu'à sa présentation dans un rapport/devant un tribunal. Son "
                "but est de pouvoir répondre clairement à une question future telle que "
                "\"cette preuve a-t-elle pu être altérée, quelqu'un y a-t-il touché ?\".\n\n"
                "Pendant l'acquisition, Chameleon écrit automatiquement CHAQUE action "
                "qu'il effectue (connexion établie, disque verrouillé/non verrouillé, "
                "quel bloc a été acquis, hash vérifié, connexion interrompue/reprise, "
                "quelle méthode réseau a été utilisée, etc.) horodatée dans un fichier "
                "journal. Ce journal est inclus dans le rapport généré une fois "
                "l'opération terminée.\n\n"
                "Un CHOIX que vous faites à certaines étapes est également enregistré "
                "dans cette chaîne (p. ex. ignorer la vérification d'identité du "
                "serveur, utiliser VPN/Tor). Cela ne signifie pas \"quelque chose de "
                "caché/incorrect a été fait\" -- au contraire, c'est un enregistrement "
                "transparent de ce qui a exactement été activé ou non comme contrôles "
                "de sécurité lors de cette acquisition."
            ),
        },
    },
    {
        "key": "hash_verification",
        "title": {
            "tr": "Hash / Bütünlük Doğrulaması Nedir?",
            "en": "What Is Hash / Integrity Verification?",
            "es": "¿Qué es la Verificación de Hash / Integridad?",
            "de": "Was ist Hash-/Integritätsprüfung?",
            "pt": "O Que É Verificação de Hash / Integridade?",
            "fr": "Qu'est-ce que la Vérification de Hash / Intégrité ?",
        },
        "body": {
            "tr": (
                "Hash, bir verinin (dosya, disk bloğu) içeriğinden matematiksel olarak "
                "üretilen, o veriye özgü kısa bir \"parmak izi\"dir (Chameleon SHA-256 "
                "kullanır). Verinin tek bir baytı bile değişse, hash tamamen farklı "
                "çıkar.\n\n"
                "Chameleon, aldığı her parçanın hash'ini hem hedef cihazda hem kendi "
                "bilgisayarınızda ayrı ayrı hesaplar ve karşılaştırır. İkisi "
                "eşleşiyorsa, verinin aktarım sırasında bozulmadan/değişmeden geldiği "
                "kanıtlanmış olur. İmaj tamamlanınca bütün dosyanın hash'i de "
                "hesaplanıp rapora yazılır -- ileride birinin \"bu imaj dosyası "
                "orijinal alınan veriyle aynı mı?\" sorusunu, imajı yeniden hesaplayıp "
                "rapordaki hash'le karşılaştırarak objektif şekilde cevaplamasını "
                "sağlar.\n\n"
                "Not: hash, verinin aktarım sırasında bozulup bozulmadığını kanıtlar -- "
                "verinin gerçekten hangi cihazdan geldiğini değil (bkz. \"Sunucu Kimlik "
                "Doğrulama\")."
            ),
            "en": (
                "A hash is a short \"fingerprint\", unique to a piece of data (a file, "
                "a disk block), computed mathematically from its content (Chameleon "
                "uses SHA-256). If even a single byte of the data changes, the hash "
                "comes out completely different.\n\n"
                "Chameleon computes and compares the hash of every chunk it acquires "
                "separately on both the target device and on your own computer. If the "
                "two match, it is proven that the data arrived without "
                "corruption/change during transfer. Once the image is complete, the "
                "hash of the whole file is also computed and written to the report -- "
                "so that in the future, anyone asking \"is this image file the same as "
                "the data originally acquired?\" can answer it objectively, by "
                "recomputing the image's hash and comparing it against the one in the "
                "report.\n\n"
                "Note: a hash proves whether the data was corrupted during transfer -- "
                "not which device it actually came from (see \"What Is Host Key "
                "Verification?\")."
            ),
            "es": (
                "Un hash es una breve \"huella digital\", única para un dato (un "
                "archivo, un bloque de disco), generada matemáticamente a partir de su "
                "contenido (Chameleon usa SHA-256). Si cambia aunque sea un solo byte "
                "del dato, el hash resulta completamente distinto.\n\n"
                "Chameleon calcula y compara el hash de cada fragmento que obtiene por "
                "separado, tanto en el dispositivo destino como en su propio equipo. Si "
                "ambos coinciden, queda demostrado que los datos llegaron sin "
                "corromperse/cambiar durante la transferencia. Al completarse la "
                "imagen, también se calcula el hash del archivo completo y se escribe "
                "en el informe -- para que en el futuro, cualquiera que se pregunte "
                "\"¿este archivo de imagen es igual a los datos originalmente "
                "obtenidos?\" pueda responderlo de forma objetiva, recalculando el hash "
                "de la imagen y comparándolo con el del informe.\n\n"
                "Nota: el hash demuestra si los datos se corrompieron durante la "
                "transferencia -- no de qué dispositivo provienen realmente (véase "
                "\"¿Qué es la Verificación de Identidad del Servidor?\")."
            ),
            "de": (
                "Ein Hash ist ein kurzer, für ein Datenstück (eine Datei, einen "
                "Festplattenblock) eindeutiger \"Fingerabdruck\", der mathematisch aus "
                "dessen Inhalt berechnet wird (Chameleon verwendet SHA-256). Ändert "
                "sich auch nur ein einziges Byte der Daten, fällt der Hash vollständig "
                "anders aus.\n\n"
                "Chameleon berechnet und vergleicht den Hash jedes erfassten Teils "
                "getrennt sowohl auf dem Zielgerät als auch auf Ihrem eigenen "
                "Computer. Stimmen beide überein, ist bewiesen, dass die Daten "
                "unbeschädigt/unverändert während der Übertragung angekommen sind. "
                "Nach Abschluss des Abbilds wird zusätzlich der Hash der gesamten "
                "Datei berechnet und in den Bericht geschrieben -- damit künftig "
                "jeder, der fragt \"ist diese Abbilddatei identisch mit den "
                "ursprünglich erfassten Daten?\", dies objektiv beantworten kann, "
                "indem der Hash des Abbilds neu berechnet und mit dem im Bericht "
                "verglichen wird.\n\n"
                "Hinweis: Der Hash beweist, ob die Daten während der Übertragung "
                "beschädigt wurden -- nicht, von welchem Gerät sie tatsächlich stammen "
                "(siehe \"Was ist Server-Identitätsprüfung?\")."
            ),
            "pt": (
                "Um hash é uma pequena \"impressão digital\", exclusiva de um dado (um "
                "arquivo, um bloco de disco), calculada matematicamente a partir do "
                "seu conteúdo (o Chameleon usa SHA-256). Se até mesmo um único byte do "
                "dado mudar, o hash sai completamente diferente.\n\n"
                "O Chameleon calcula e compara o hash de cada parte que adquire "
                "separadamente, tanto no dispositivo alvo quanto no seu próprio "
                "computador. Se os dois coincidirem, fica comprovado que os dados "
                "chegaram sem corrupção/alteração durante a transferência. Ao concluir "
                "a imagem, o hash do arquivo inteiro também é calculado e gravado no "
                "relatório -- para que, no futuro, qualquer pessoa que pergunte \"esse "
                "arquivo de imagem é igual aos dados originalmente obtidos?\" possa "
                "responder de forma objetiva, recalculando o hash da imagem e "
                "comparando com o do relatório.\n\n"
                "Observação: o hash comprova se os dados foram corrompidos durante a "
                "transferência -- não de qual dispositivo eles realmente vieram (veja "
                "\"O Que É Verificação de Identidade do Servidor?\")."
            ),
            "fr": (
                "Un hash est une courte \"empreinte\", propre à une donnée (un "
                "fichier, un bloc de disque), calculée mathématiquement à partir de "
                "son contenu (Chameleon utilise SHA-256). Si ne serait-ce qu'un seul "
                "octet de la donnée change, le hash devient complètement différent.\n\n"
                "Chameleon calcule et compare le hash de chaque fragment acquis "
                "séparément, à la fois sur l'appareil cible et sur votre propre "
                "ordinateur. Si les deux correspondent, il est prouvé que les données "
                "sont arrivées sans corruption/modification pendant le transfert. Une "
                "fois l'image terminée, le hash du fichier entier est également "
                "calculé et inscrit dans le rapport -- afin qu'à l'avenir, quiconque se "
                "demande \"ce fichier image est-il identique aux données originalement "
                "acquises ?\" puisse y répondre objectivement, en recalculant le hash "
                "de l'image et en le comparant à celui du rapport.\n\n"
                "Remarque : le hash prouve si les données ont été corrompues pendant le "
                "transfert -- pas de quel appareil elles proviennent réellement (voir "
                "\"Qu'est-ce que la Vérification d'Identité du Serveur ?\")."
            ),
        },
    },
    {
        "key": "ram_full_mode_driver",
        "title": {
            "tr": "RAM 'Full' Modu: Yönetici, Sürücü ve Secure Boot Ne Demek?",
            "en": "RAM \"Full\" Mode: What Do Administrator, Driver, and Secure Boot Mean?",
            "es": "Modo RAM \"Completo\": ¿Qué Significan Administrador, Controlador y Secure Boot?",
            "de": "RAM-\"Full\"-Modus: Was Bedeuten Administrator, Treiber und Secure Boot?",
            "pt": "Modo RAM \"Completo\": O Que Significam Administrador, Driver e Secure Boot?",
            "fr": "Mode RAM \"Complet\" : Que Signifient Administrateur, Pilote et Secure Boot ?",
        },
        "body": {
            "tr": (
                "RAM İmajı Al ekranında iki mod vardır:\n\n"
                "Process Dump: sadece TEK BİR programın o anki bellek kullanımını "
                "alır. Yönetici yetkisi gerekmez, hızlıdır.\n\n"
                "Full: bilgisayarın TÜM sistem belleğini alır -- açık tüm programların "
                "ve işletim sisteminin o anki tam görüntüsü. Bunun için Windows'un "
                "normalde izin vermediği düşük seviyeli bir erişim gerekir; bu erişimi "
                "sağlayan küçük yazılım parçasına \"sürücü\" (driver) denir.\n\n"
                "Windows, güvenlik için resmi olarak imzalanmamış (test amaçlı) "
                "sürücülerin yüklenmesini varsayılan olarak engeller. \"Test-signing\" "
                "bu engeli açan bir Windows ayarıdır -- açıldığında bilgisayar bunu "
                "ekranda bir filigranla gösterir. Bu ayar, bilgisayarın başka bir "
                "güvenlik özelliği olan \"Secure Boot\"un (açılış sırasında sadece "
                "güvenilir/imzalı yazılımların çalışmasını sağlayan koruma) "
                "kapatılmasını gerektirebilir.\n\n"
                "Bu yüzden Full mod, inceleyeceğiniz bilgisayarda DEĞİL, KENDİ "
                "makinenizde önceden hazırlanmalıdır -- rastgele bir hedef cihazda bu "
                "ayarları değiştirmek pratikte çoğu zaman mümkün olmaz ve delil "
                "bütünlüğünü riske atar."
            ),
            "en": (
                "The RAM Image screen has two modes:\n\n"
                "Process Dump: acquires the current memory usage of only ONE program. "
                "No administrator privileges needed, fast.\n\n"
                "Full: acquires the computer's ENTIRE system memory -- a complete "
                "snapshot of all running programs and the operating system at that "
                "moment. This requires a low-level access that Windows doesn't "
                "normally allow; the small piece of software that provides this access "
                "is called a \"driver\".\n\n"
                "For security, Windows blocks the loading of unofficially-signed "
                "(test-purpose) drivers by default. \"Test-signing\" is a Windows "
                "setting that lifts this block -- once enabled, the computer shows "
                "this with a watermark on screen. This setting may require disabling "
                "another security feature of the computer, \"Secure Boot\" (a "
                "protection that ensures only trusted/signed software runs during "
                "startup).\n\n"
                "That's why Full mode must be prepared in advance on YOUR OWN machine, "
                "NOT on the computer you'll be examining -- changing these settings on "
                "an arbitrary target device is usually impractical, and risks the "
                "integrity of the evidence."
            ),
            "es": (
                "La pantalla de Imagen de RAM tiene dos modos:\n\n"
                "Volcado de Proceso: obtiene el uso de memoria actual de UN SOLO "
                "programa. No requiere privilegios de administrador, es rápido.\n\n"
                "Completo: obtiene TODA la memoria del sistema del equipo -- una "
                "instantánea completa de todos los programas en ejecución y del "
                "sistema operativo en ese momento. Esto requiere un acceso de bajo "
                "nivel que Windows normalmente no permite; la pequeña pieza de "
                "software que proporciona este acceso se llama \"controlador\" "
                "(driver).\n\n"
                "Por seguridad, Windows bloquea de forma predeterminada la carga de "
                "controladores no firmados oficialmente (con fines de prueba). "
                "\"Test-signing\" es una configuración de Windows que levanta este "
                "bloqueo -- una vez activada, el equipo lo muestra con una marca de "
                "agua en pantalla. Esta configuración puede requerir desactivar otra "
                "función de seguridad del equipo, \"Secure Boot\" (una protección que "
                "garantiza que solo se ejecute software de confianza/firmado durante "
                "el arranque).\n\n"
                "Por eso el modo Completo debe prepararse de antemano en SU PROPIO "
                "equipo, NO en el equipo que va a examinar -- cambiar estos ajustes en "
                "un dispositivo destino arbitrario suele ser poco práctico y pone en "
                "riesgo la integridad de la evidencia."
            ),
            "de": (
                "Der Bildschirm RAM-Image hat zwei Modi:\n\n"
                "Prozessabbild: erfasst die aktuelle Speichernutzung nur EINES "
                "Programms. Keine Administratorrechte nötig, schnell.\n\n"
                "Vollständig: erfasst den GESAMTEN Systemspeicher des Computers -- "
                "eine vollständige Momentaufnahme aller laufenden Programme und des "
                "Betriebssystems zu diesem Zeitpunkt. Dies erfordert einen "
                "Low-Level-Zugriff, den Windows normalerweise nicht erlaubt; das "
                "kleine Software-Stück, das diesen Zugriff ermöglicht, wird "
                "\"Treiber\" genannt.\n\n"
                "Aus Sicherheitsgründen blockiert Windows standardmäßig das Laden "
                "nicht offiziell signierter (zu Testzwecken bestimmter) Treiber. "
                "\"Test-Signing\" ist eine Windows-Einstellung, die diese Blockade "
                "aufhebt -- ist sie aktiviert, zeigt der Computer dies mit einem "
                "Wasserzeichen auf dem Bildschirm an. Diese Einstellung kann "
                "erfordern, dass eine weitere Sicherheitsfunktion des Computers, "
                "\"Secure Boot\" (ein Schutz, der sicherstellt, dass beim Start nur "
                "vertrauenswürdige/signierte Software läuft), deaktiviert wird.\n\n"
                "Deshalb muss der Full-Modus vorab auf IHREM EIGENEN Rechner "
                "vorbereitet werden, NICHT auf dem Computer, den Sie untersuchen "
                "werden -- das Ändern dieser Einstellungen auf einem beliebigen "
                "Zielgerät ist in der Praxis meist nicht möglich und gefährdet die "
                "Integrität der Beweismittel."
            ),
            "pt": (
                "A tela de Imagem de RAM tem dois modos:\n\n"
                "Dump de Processo: obtém o uso de memória atual de APENAS UM "
                "programa. Não requer privilégios de administrador, é rápido.\n\n"
                "Completo: obtém TODA a memória do sistema do computador -- um "
                "instantâneo completo de todos os programas em execução e do sistema "
                "operacional naquele momento. Isso requer um acesso de baixo nível "
                "que o Windows normalmente não permite; o pequeno pedaço de software "
                "que fornece esse acesso é chamado de \"driver\".\n\n"
                "Por segurança, o Windows bloqueia por padrão o carregamento de "
                "drivers não assinados oficialmente (para fins de teste). "
                "\"Test-signing\" é uma configuração do Windows que remove esse "
                "bloqueio -- quando ativada, o computador mostra isso com uma marca "
                "d'água na tela. Essa configuração pode exigir a desativação de outro "
                "recurso de segurança do computador, o \"Secure Boot\" (uma proteção "
                "que garante que apenas software confiável/assinado seja executado "
                "durante a inicialização).\n\n"
                "Por isso o modo Completo deve ser preparado com antecedência na SUA "
                "PRÓPRIA máquina, NÃO no computador que você vai examinar -- alterar "
                "essas configurações em um dispositivo alvo qualquer costuma ser "
                "impraticável na prática e coloca em risco a integridade da "
                "evidência."
            ),
            "fr": (
                "L'écran Image RAM propose deux modes :\n\n"
                "Dump de Processus : acquiert l'utilisation mémoire actuelle d'UN SEUL "
                "programme. Aucun privilège administrateur requis, rapide.\n\n"
                "Complet : acquiert TOUTE la mémoire système de l'ordinateur -- un "
                "instantané complet de tous les programmes en cours d'exécution et du "
                "système d'exploitation à ce moment. Cela nécessite un accès de bas "
                "niveau que Windows n'autorise normalement pas ; le petit logiciel qui "
                "fournit cet accès est appelé \"pilote\" (driver).\n\n"
                "Pour des raisons de sécurité, Windows bloque par défaut le "
                "chargement de pilotes non signés officiellement (à des fins de "
                "test). Le \"test-signing\" est un paramètre Windows qui lève ce "
                "blocage -- une fois activé, l'ordinateur l'indique par un filigrane "
                "à l'écran. Ce paramètre peut nécessiter la désactivation d'une autre "
                "fonction de sécurité de l'ordinateur, le \"Secure Boot\" (une "
                "protection garantissant que seul un logiciel fiable/signé s'exécute "
                "au démarrage).\n\n"
                "C'est pourquoi le mode Complet doit être préparé à l'avance sur "
                "VOTRE PROPRE machine, PAS sur l'ordinateur que vous allez examiner "
                "-- modifier ces paramètres sur un appareil cible quelconque est "
                "généralement impraticable et met en péril l'intégrité de la preuve."
            ),
        },
    },
    {
        "key": "tor_onion_operator_key",
        "title": {
            "tr": "Tor, .onion Adresi ve Operatör Anahtarı Nasıl Çalışır?",
            "en": "How Do Tor, the .onion Address, and the Operator Key Work?",
            "es": "¿Cómo Funcionan Tor, la Dirección .onion y la Clave de Operador?",
            "de": "Wie Funktionieren Tor, die .onion-Adresse und der Operator-Schlüssel?",
            "pt": "Como Funcionam o Tor, o Endereço .onion e a Chave de Operador?",
            "fr": "Comment Fonctionnent Tor, l'Adresse .onion et la Clé d'Opérateur ?",
        },
        "body": {
            "tr": (
                "Tor, internet trafiğini tek bir doğrudan bağlantı yerine, dünya "
                "genelinde gönüllülerin çalıştırdığı birden fazla sunucu (röle) "
                "üzerinden şifreli katmanlar hâlinde yönlendiren bir ağdır -- bu "
                "sayede trafiğin nereden nereye gittiği ağ üzerinde izlenemez. Bedeli: "
                "birden fazla sunucudan geçtiği için gecikme yüksek, hız düşüktür.\n\n"
                "\".onion\" adresi normal bir internet adresi (IP/alan adı) DEĞİLDİR -- "
                "sadece Tor ağı içinde anlam ifade eden, dışarıdan bulunamayan bir "
                "adrestir. Taşınabilir kit hedef cihazda çalıştırıldığında bu adresi "
                "kendiliğinden üretir; hiçbir merkezi sunucuya kayıt yapılmaz, adres "
                "SADECE o kit çalıştığı sürece var olur.\n\n"
                "Operatör anahtarı, bu .onion adresine sadece SİZİN bağlanabilmenizi "
                "sağlayan bir kimlik doğrulama anahtarıdır. Adresi ele geçiren biri "
                "bile bu anahtar olmadan bağlanamaz -- yani güvenlik \"adres gizli "
                "kalsın\" değil, \"adres bilinse bile anahtarsız işe yaramasın\" "
                "prensibine dayanır. Bu yüzden operatör anahtarınızı saha "
                "ziyaretinden ÖNCE, kiti hazırlayacak/götürecek kişiye güvenli bir "
                "şekilde iletmeniz gerekir."
            ),
            "en": (
                "Tor is a network that routes internet traffic through multiple "
                "servers (relays) run by volunteers worldwide, in encrypted layers, "
                "instead of a single direct connection -- this makes it impossible to "
                "trace where the traffic is going to/from on the network. The cost: "
                "because it passes through multiple servers, latency is high and speed "
                "is low.\n\n"
                "A \".onion\" address is NOT a normal internet address (IP/domain "
                "name) -- it's an address that only has meaning within the Tor network "
                "and cannot be found from outside it. When the portable kit is run on "
                "the target device, it generates this address on its own; nothing is "
                "registered with any central server, and the address only exists for "
                "as long as that kit is running.\n\n"
                "The operator key is an authentication key that lets ONLY YOU connect "
                "to this .onion address. Even someone who obtains the address cannot "
                "connect without this key -- meaning the security doesn't rest on "
                "\"keeping the address secret\", but on the principle that \"even if "
                "the address is known, it's useless without the key\". This is why you "
                "must securely deliver your operator key to the person preparing/"
                "taking the kit BEFORE the site visit."
            ),
            "es": (
                "Tor es una red que enruta el tráfico de internet a través de "
                "múltiples servidores (repetidores) operados por voluntarios en todo "
                "el mundo, en capas cifradas, en lugar de una única conexión directa "
                "-- esto hace imposible rastrear en la red de dónde a dónde va el "
                "tráfico. El coste: al pasar por varios servidores, la latencia es "
                "alta y la velocidad es baja.\n\n"
                "Una dirección \".onion\" NO es una dirección de internet normal "
                "(IP/nombre de dominio) -- es una dirección que solo tiene sentido "
                "dentro de la red Tor y no se puede encontrar desde fuera de ella. "
                "Cuando el kit portátil se ejecuta en el dispositivo destino, genera "
                "esta dirección por sí mismo; no se registra nada en ningún servidor "
                "central, y la dirección solo existe mientras ese kit esté en "
                "ejecución.\n\n"
                "La clave de operador es una clave de autenticación que permite que "
                "SOLO USTED pueda conectarse a esta dirección .onion. Incluso alguien "
                "que obtenga la dirección no puede conectarse sin esta clave -- es "
                "decir, la seguridad no se basa en \"mantener la dirección en "
                "secreto\", sino en el principio de que \"aunque se conozca la "
                "dirección, resulta inútil sin la clave\". Por eso debe entregar su "
                "clave de operador de forma segura a la persona que preparará/llevará "
                "el kit ANTES de la visita al sitio."
            ),
            "de": (
                "Tor ist ein Netzwerk, das Internetverkehr statt über eine einzige "
                "Direktverbindung über mehrere weltweit von Freiwilligen betriebene "
                "Server (Relays) in verschlüsselten Schichten weiterleitet -- dadurch "
                "lässt sich im Netzwerk nicht nachverfolgen, woher der Verkehr kommt "
                "und wohin er geht. Der Preis dafür: Da er über mehrere Server läuft, "
                "ist die Latenz hoch und die Geschwindigkeit niedrig.\n\n"
                "Eine \".onion\"-Adresse ist KEINE normale Internetadresse "
                "(IP/Domainname) -- sie ist eine Adresse, die nur innerhalb des "
                "Tor-Netzwerks Bedeutung hat und von außerhalb nicht gefunden werden "
                "kann. Wenn das tragbare Kit auf dem Zielgerät ausgeführt wird, "
                "erzeugt es diese Adresse selbstständig; nichts wird bei einem "
                "zentralen Server registriert, und die Adresse existiert nur, solange "
                "dieses Kit läuft.\n\n"
                "Der Operator-Schlüssel ist ein Authentifizierungsschlüssel, der NUR "
                "IHNEN erlaubt, sich mit dieser .onion-Adresse zu verbinden. Selbst "
                "jemand, der die Adresse erlangt, kann sich ohne diesen Schlüssel "
                "nicht verbinden -- die Sicherheit beruht also nicht darauf, \"die "
                "Adresse geheim zu halten\", sondern auf dem Prinzip, dass \"selbst "
                "wenn die Adresse bekannt ist, sie ohne Schlüssel nutzlos bleibt\". "
                "Deshalb müssen Sie Ihren Operator-Schlüssel VOR dem Vor-Ort-Besuch "
                "sicher an die Person übergeben, die das Kit vorbereitet/mitnimmt."
            ),
            "pt": (
                "O Tor é uma rede que roteia o tráfego de internet por meio de vários "
                "servidores (retransmissores) operados por voluntários ao redor do "
                "mundo, em camadas criptografadas, em vez de uma única conexão direta "
                "-- isso torna impossível rastrear na rede de onde para onde o "
                "tráfego vai. O custo: por passar por vários servidores, a latência é "
                "alta e a velocidade é baixa.\n\n"
                "Um endereço \".onion\" NÃO é um endereço de internet normal (IP/nome "
                "de domínio) -- é um endereço que só tem significado dentro da rede "
                "Tor e não pode ser encontrado de fora dela. Quando o kit portátil é "
                "executado no dispositivo alvo, ele gera esse endereço sozinho; nada "
                "é registrado em nenhum servidor central, e o endereço só existe "
                "enquanto aquele kit estiver em execução.\n\n"
                "A chave de operador é uma chave de autenticação que permite que "
                "SOMENTE VOCÊ se conecte a esse endereço .onion. Mesmo alguém que "
                "obtenha o endereço não consegue se conectar sem essa chave -- ou "
                "seja, a segurança não se baseia em \"manter o endereço em segredo\", "
                "mas no princípio de que \"mesmo que o endereço seja conhecido, ele é "
                "inútil sem a chave\". Por isso você precisa entregar sua chave de "
                "operador de forma segura à pessoa que vai preparar/levar o kit ANTES "
                "da visita ao local."
            ),
            "fr": (
                "Tor est un réseau qui achemine le trafic internet à travers "
                "plusieurs serveurs (relais) exploités par des bénévoles dans le "
                "monde entier, en couches chiffrées, au lieu d'une seule connexion "
                "directe -- cela rend impossible de suivre sur le réseau d'où vers où "
                "va le trafic. Le prix à payer : passant par plusieurs serveurs, la "
                "latence est élevée et la vitesse est faible.\n\n"
                "Une adresse \".onion\" n'est PAS une adresse internet normale "
                "(IP/nom de domaine) -- c'est une adresse qui n'a de sens qu'au sein "
                "du réseau Tor et ne peut pas être trouvée depuis l'extérieur. "
                "Lorsque le kit portable est exécuté sur l'appareil cible, il génère "
                "cette adresse de lui-même ; rien n'est enregistré auprès d'un "
                "quelconque serveur central, et l'adresse n'existe que tant que ce "
                "kit fonctionne.\n\n"
                "La clé d'opérateur est une clé d'authentification qui permet à VOUS "
                "SEUL de vous connecter à cette adresse .onion. Même quelqu'un qui "
                "obtiendrait l'adresse ne peut pas s'y connecter sans cette clé -- "
                "autrement dit, la sécurité ne repose pas sur le fait de \"garder "
                "l'adresse secrète\", mais sur le principe que \"même connue, "
                "l'adresse est inutile sans la clé\". C'est pourquoi vous devez "
                "remettre votre clé d'opérateur de manière sécurisée à la personne "
                "qui préparera/emportera le kit AVANT la visite sur site."
            ),
        },
    },
]


def get_topic(key, lang="tr"):
    """key'e karsilik gelen konuyu, title/body lang'a cevrilmis duz string
    olarak doner (yoksa None). lang icin ceviri yoksa "tr"ye duser."""
    for topic in HELP_TOPICS:
        if topic["key"] == key:
            return {
                "key": key,
                "title": topic["title"].get(lang, topic["title"]["tr"]),
                "body": topic["body"].get(lang, topic["body"]["tr"]),
            }
    return None
